### PR TITLE
TRIZ-3363 Customizing color for 'Get Started' button

### PR DESCRIPTION
**Pull request by marcelomogrovejo**
@eweise @johntowell @LowellBateman

### CODE REVIEW

**Comment by LowellBateman** [comment]
:+1:

**Comment by johntowell** [comment]
I would add the new property to the required block.

**Comment by marcelomogrovejo** [comment]
which required block? where?

**Comment by LowellBateman** [comment]
api/v2/website/schema/website.res.json @ line 52

**Comment by marcelomogrovejo** [comment]
Done guys :-)

**Comment by johntowell** [comment]
:+1:

**Comment by johntowell** [comment]
https://github.com/trizic/trizic-api-docs/blob/master/README.md

Make sure to follow directions here next.

**Comment by marcelomogrovejo** [comment]
Sure!

**Pull request merged**
