### PR TITLE
PCU-53: Add data summary route and harden data schema

### PR DESCRIPTION
**Pull request by johntowell**
The data/summary route returns performance information for all periods without the accountSeries (graph) information.

@abuecker @MaxiSanchez @eweise @bondricek @antoinemeyer @LowellBateman

### CODE REVIEW

**Comment by eweise** [comment]
:+1:

**Comment by johntowell** [comment]
@pablodicosta @eselman One more thumbs up to unblock @MaxiSanchez !

**Comment by eweise** [comment]
:+1:

**Comment by johntowell** [comment]
Ha! One more thumbs up (that is not @eweise ) to unblock @MaxiSanchez ! Since we need 2 thumbs up for this repo!

**Comment by eselman** [comment]
:+1

**Comment by johntowell** [comment]
Thanks guys!

**Pull request merged**
