### PR TITLE
feat(CB2-23): retrieve all the invoices of a firm with updated routes

### PR DESCRIPTION
**Pull request by antoinemeyer**
using routes defined in https://trizic.atlassian.net/browse/CB2-52

### CODE REVIEW

**Comment by antoinemeyer** [comment]
@kvhswong @bondricek @eweise @LowellBateman @johntowell  please review

**Comment by kvhswong** [comment]
@antoinemeyer, I don't know if this is an issue with me locally but when I load the API I get a lot of extraneous routes for the advisor. Can you take a look and let me know if this is something wrong on my end, or if it is something with the PR please?

**Comment by antoinemeyer** [comment]
I haven't deleted all the previous routes so that it doesn't break existing builds of advisor-api (we use an unversioned api and advisor-api build is now linked to the latest deployment of this repo).
I can clean everything up in this PR if you prefer.

**Comment by kvhswong** [comment]
I have an outstanding PR with the updated routes. I'll ask Brad tomorrow if he needs the existing routes. My guess would be no, but let's confirm with him tomorrow. Thanks for updating the fee schedule routes in your PR.

**Comment by antoinemeyer** [comment]
*Deleted all routes.
Advisor routes are now:
`09:30:19:781 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/fees/{groupKey}/pending}
09:30:19:781 Action{type='DELETE', resource=/v2/advisor/{advisorId}/client/billing/fees/{groupKey}/pending}
09:30:19:781 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/fees/{groupKey}/{feeScheduleId}}
09:30:19:781 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/fees/{groupKey}}
09:30:19:781 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/fees/{groupKey}/active}
09:30:19:782 Action{type='DELETE', resource=/v2/advisor/{advisorId}/client/billing/fees/{groupKey}/active}
09:30:19:782 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees/{groupKey}/active}
09:30:19:782 Action{type='DELETE', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees/{groupKey}/active}
09:30:19:782 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees/{groupKey}/pending}
09:30:19:782 Action{type='DELETE', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees/{groupKey}/pending}
09:30:19:782 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees/{groupKey}/{feeScheduleId}}
09:30:19:782 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/invoices/{clientId}}
09:30:19:783 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/invoices}
09:30:19:783 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/invoice/{invoiceNumber}}
09:30:19:783 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/fees}
09:30:19:784 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/invoices}
09:30:19:784 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees/{groupKey}}
09:30:19:784 Action{type='POST', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees}
09:30:19:784 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/fees}
09:30:19:784 Action{type='POST', resource=/v2/advisor/{advisorId}/client/billing/fees}
09:30:19:784 Action{type='GET', resource=/v2/advisor/{advisorId}/client/billing/fees}
09:30:19:785 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/invoices/{clientId}}
09:30:19:785 Action{type='POST', resource=/v2/advisor/{advisorId}/client/{clientId}/fees/calc}
09:30:19:786 Action{type='GET', resource=/v2/advisor/{advisorId}/client/{clientId}/billing/invoice/{invoiceNumber}}
`

**Comment by antoinemeyer** [comment]
Updated routes:
`/v2/advisor/{advisorId}/client/billing/feeSchedule - GET
/v2/advisor/{advisorId}/client/billing/feeSchedule/group/{groupKey} - GET
/v2/advisor/{advisorId}/client/billing/feeSchedule/group/{groupKey}/active - GET
/v2/advisor/{advisorId}/client/billing/feeSchedule/group/{groupKey}/pending - GET
/v2/advisor/{advisorId}/client/billing/feeSchedule/group/{groupKey}/pending - DELETE
/v2/advisor/{advisorId}/client/billing/feeSchedule/{feeScheduleId}/group/{groupKey} - GET
/v2/advisor/{advisorId}/client/billing/feeSchedules - POST
/v2/advisor/{advisorId}/client/billing/feeSchedules - GET
/v2/advisor/{advisorId}/client/billing/feeSchedules/group/{groupKey} - GET
/v2/advisor/{advisorId}/client/billing/invoice/{invoiceNumber} - GET
/v2/advisor/{advisorId}/client/billing/invoices - GET
/v2/advisor/{advisorId}/client/{clientId}/billing/feeSchedule - GET
/v2/advisor/{advisorId}/client/{clientId}/billing/invoice/{invoiceNumber} - GET
/v2/advisor/{advisorId}/client/{clientId}/billing/invoices - GET`

**Comment by kvhswong** [comment]
This route should return a single fee schedule as opposed to a list for the GET, /v2/advisor/{advisorId}/client/billing/feeSchedule.

**Comment by kvhswong** [comment]
Otherwise all the other routes look good.

**Comment by antoinemeyer** [comment]
*updated return type of `/v2/advisor/{advisorId}/client/billing/feeSchedule`

**Comment by kvhswong** [comment]
👍

**Pull request merged**
