### PR TITLE
feat(build): setup `npm pack` to create an npm package

### PR DESCRIPTION
**Pull request by abuecker**

### CODE REVIEW

**Comment by abuecker** [comment]
@johntowell || @eweise plz review

**Comment by eweise** [comment]
95 files changed? dtrace-provider? Why do we need that for documentation and a mock server?

**Comment by johntowell** [comment]
:+1:

**Comment by abuecker** [comment]
Dtrace is part of the `restify` module that the mock server uses.

80+ files are removing `./dist` from version control.

**Pull request merged**
