### PR TITLE
feat: adding invoice routes

### PR DESCRIPTION
**Pull request by antoinemeyer**
@bondricek @eweise @johntowell please review

### CODE REVIEW

**Comment by antoinemeyer** [comment]
*bump

**Comment by johntowell** [comment]
Not familiar with the roject. Are you guys using the json schema for validation or only to generate mocks? Or..?

**Comment by bondricek** [comment]
yes we want to use it for validation, but its not in place yet.   It could also be used for mocks, but ui hasnt started yet.

**Comment by johntowell** [comment]
If you are using it for validation then I think you should be using the required keyword

http://spacetelescope.github.io/understanding-json-schema/reference/object.html?highlight=required#required

and also use http://spacetelescope.github.io/understanding-json-schema/reference/object.html?highlight=required#pattern-properties

additionalProperties=false

otherwise the schema isn't that useful for validation since you can basically return any combination of properties and it will validate.

**Comment by antoinemeyer** [comment]
added required fields and additionalProperties=false*

**Comment by antoinemeyer** [comment]
@bondricek @eweise @johntowell please review

**Comment by eweise** [comment]
What does the url look like? I see /{clientId}/{invoiceId} at first glance seems odd to have to numbers together like that.

**Comment by johntowell** [comment]
required takes an array of properties 

http://spacetelescope.github.io/understanding-json-schema/reference/object.html#required-properties

remember required just means the property will be present. Which in our case is usually all of them. The fact that it can be null does not change the fact that it is present.

**Comment by antoinemeyer** [comment]
Thanks John. I've updated the required to be v4 compliant (and not v3).
The json schema tool of jackson still doesn't handle the 'required' properly for v4 :((https://github.com/FasterXML/jackson-module-jsonSchema/issues/9)  (does't seem that hard to implement though ...)
Is there any better tool we could use to keep in sync our json and java schemas?
Ideally that whole layer should be mostly auto-generated.
Is that api-docs just used during test phase btw?

**Comment by antoinemeyer** [comment]
@eweise, yeah, the urls are:
"billing/invoice/{clientId}/{invoiceNumber}"
"billing/invoices/{clientId}"
It could have been prettier :rowboat:

**Comment by eweise** [comment]
Wondering if the url should look more like 

/v2/client/{clientId}/billing/invoice/{invoiceNumber}"
/v2/client/{clientId}/billing/invoices/

**Comment by johntowell** [comment]
We are validating the json in the trizic-rest project controller tests using 
https://javalibs.com/artifact/com.jayway.restassured/json-schema-validator

Man... whoever created those awesome controller integration tests did a bang up job!

**Comment by antoinemeyer** [comment]
Well instead of writing A and B and checking that A and B work together, why not create A and generate B from it?

**Comment by antoinemeyer** [comment]
@bondricek @eweise @johntowell @LowellBateman please review

**Comment by johntowell** [comment]
ok with me 👍

**Pull request merged**
