### PR TITLE
TRIZ-3266 Checks if an email is already in use routes

### PR DESCRIPTION
**Pull request by antoinemeyer**
@johntowell @eweise please review

### CODE REVIEW

**Comment by johntowell** [comment]
looks good, what about response? you can use the common ones

        body:
          application/json:
            schema: !include ../common/schema/generic.res.json
            example: !include ../common/examples/generic.res.json

**Comment by antoinemeyer** [comment]
I don't want a response! just a http status!

**Comment by johntowell** [comment]
Our convention is to always return a response. We are using ResultStatusDto for all our routes. I agree that the status (OK, ERROR) is redundant, but nevertheless it's our current convention and consistency is very important for maintainability.

**Comment by eweise** [comment]
having the same structure for all responses makes it easy on the client to parse as well.

**Comment by antoinemeyer** [comment]
So everything is a 200 ?
Our poor rest api is not really restful :(

**Comment by johntowell** [comment]
No, you can return http error codes, but those would also have a json response with status: 'ERROR'

**Comment by antoinemeyer** [comment]
oh I see, ok will try to add that

**Comment by antoinemeyer** [comment]
all right, I have added the response generic info.
@johntowell @eweise please review

**Comment by eweise** [comment]
:+1:

**Comment by johntowell** [comment]
:+1:  I'm modifying this as well, so I can update the shrinkwrap

**Pull request merged**
