### PR TITLE
remove dist folder from git

### PR DESCRIPTION
**Pull request by johntowell**
The dist folder is generated

### CODE REVIEW

**Comment by johntowell** [comment]
@abuecker @eweise @LowellBateman @antoinemeyer

**Comment by eweise** [comment]
:+1:

**Comment by antoinemeyer** [comment]
no test ? :p
:+1:

**Comment by johntowell** [comment]
thanks guys!

**Comment by LowellBateman** [comment]
:+1:

**Comment by abuecker** [comment]
No.  This needs to be there for the time being.  This project is written in ES6.  In order to import it as a module , we need to transpile it to ES5 which is in `./dist`.

I'm going to revert this and open up another ticket to investigate generating the ES5 on postinstall.

**Pull request merged**
