### PR TITLE
PCU-43: Add the ability to add/override properties to the mock response

### PR DESCRIPTION
**Pull request by johntowell**
@abuecker @antoinemeyer @eweise @bondricek @LowellBateman @pablodicosta @eselman 

Not sure why the dist changes are there? Someone forgot to check in? My changes are in server/api.js

### CODE REVIEW

**Comment by LowellBateman** [comment]
I have dist ignored in my repo

**Comment by pablodicosta** [comment]
:+1:

**Comment by LowellBateman** [comment]
:+1:

**Comment by johntowell** [comment]
dist/index.html removed

**Pull request merged**
