### PR TITLE
feat(account-create): add additional docusign form data array

### PR DESCRIPTION
**Pull request by johntowell**
@olmstead @eweise @antoinemeyer 

This is how I was thinking about handling all the additional form fields we now need to pass in to fill out the docusign documents completely.

Thoughts?

### CODE REVIEW

**Comment by eweise** [comment]
looks ok to me 🌵

**Comment by antoinemeyer** [comment]
As discussed, the more we can reuse from docusign json structure, the better it is. 
If we can pass up those json objects without extra marshalling/unmarshalling, it might be even better!

**Comment by johntowell** [comment]
show me your thumbs!

**Comment by antoinemeyer** [comment]
Do you have a PR that shows how this is handled on the server-side ? :)

**Comment by eweise** [comment]
Is a cactus not enough? 👍

**Comment by olmstead** [comment]
👍

**Comment by johntowell** [comment]
I'll work on the server side next, but I like the marshaling. That's how the rest of both APIs work (trizic-rest, and docusign) feels non standard to start using pure JSON objects. Not sure how that would even work since the marshaling layer is different for both APIs, Jackson vs. Gson.

**Pull request merged**
