### PR TITLE
Add bank instructions route /v2/consumer/account/{accountId}/bankInst…

### PR DESCRIPTION
**Pull request by eweise**
Add new route to get bank instructions for an account 

@antoinemeyer @johntowell @olmstead

### CODE REVIEW

**Comment by johntowell** [comment]
which items are required? All of them? The JSON schema is pretty useless for validation purposes without required.

**Comment by eweise** [comment]
Added required to the response fields. However this data comes from TD and their schema does not specify what is required so your mileage may vary.

http://martinfowler.com/bliki/TolerantReader.html

**Comment by johntowell** [comment]
I think Postel's Law is more applicable here since this is our API. 
> Postel's Law states that you should be liberal in what you accept and conservative in what you send. 

http://martinfowler.com/articles/enterpriseREST.html

**Comment by johntowell** [comment]
👍

**Comment by johntowell** [comment]
also required just means the property exists, I think returning null is something different

**Comment by eweise** [comment]
Nothing beats a Martin Fowler post like another Martin Fowler post.

**Comment by johntowell** [comment]
dueling fowlers

**Pull request merged**
