### PR TITLE
docs(billing): add route for calculating fees Closes: CB-14

### PR DESCRIPTION
**Pull request by eselman**
Comments: I'm not sure about the response, if after calculating the fees we generate an invoice I think is not necessary to return it here since we will have a get for invoices. What do you think?

@olmstead, @bondricek , @abuecker  could you please review?

### CODE REVIEW

**Comment by bondricek** [comment]
After thinking about this some, I'm not sure we should expose a rest endpoint for calculating fees.  Really there should be a scheduled services for each billing cycle that does the calculations, invoice generation and veo integration.

advisor api should only be for things exposed to the advisor application like creating/updating/viewing fee schedules, assigning/view fee schedules assigned to the client, viewing invoices for a client.

**Comment by abuecker** [comment]
Agreed this will probably be scheduled, but I would think we'd want a way to manually trigger it too, just in case.

**Comment by bondricek** [comment]
If we want to manually trigger the calc for a client, maybe we should make the uri more closely match the other client specific uri...  POST  /v2/advisor/client/{clientId}/fees/calc

For the response i think we have two options:
1) return just a status (204 success or 500 error)
2) return the generated invoice on success

Advantage of option 1 is the API is a simple CRUD operation with no assumptions of what the application is trying to do.  

Disadvantage of only CRUD operations is it can make the application really inefficient making repeated or multiple calls that could really be streamlined with a more aware api.  

Thoughts?

**Comment by eselman** [comment]
I can change the uri to be /v2/advisor/client/{clientId}/fees/calc.

Regarding the response, I prefer option 1, I think we can keep it simple for the moment and then evaluate the performance of the application

**Comment by eselman** [comment]
@olmstead, @bondricek , @abuecker please review my changes.

**Comment by bondricek** [comment]
:+1:

**Comment by olmstead** [comment]
:+1:

**Pull request merged**
